config/routes.rb
Rails.application.routes.draw do
	resources :diffs, only: %i[index show]
	resources :sites, only: %i[index show new create edit update destroy]
	resources :config, only: %i[index]
	resources :groups, only: %i[new create edit update destroy]
	resources :templates, only: %i[new create edit update destroy]
	# resources :access, only: %i[new create]

	get '/login', to: 'site#login'
	post '/login', to: 'site#auth'
	get '/logout', to: 'site#logout'
end

app/models/diff.rb
class Diff < ApplicationRecord
	belongs_to :site

	def self.dates
		sql = <<-SQL
			SELECT DISTINCT date_trunc('day', created_at) AS date
			FROM #{self.table_name}
			ORDER BY date ASC
		SQL
		ActiveRecord::Base.connection.execute(sql)
			.collect { |r| Date.parse r['date'] }
	end
end

app/controllers/diffs_controller.rb
class DiffsController < ApplicationController
	def index
		last = Diff.order(created_at: :desc).limit(1).first
		return redirect_to action: :show, id: last.created_at.to_date if last
	end

	DATE_DELTA = 3

	def show
		@date = Date.parse params[:id]
		dates = Diff.dates
		current = dates.index @date
		min = [0, current - DATE_DELTA].max
		max = current + DATE_DELTA
		@dates = dates[min..max]
		@diffs = Diff.where created_at: @date..@date+1
	end
end

app/helpers/diffs_helper.rb
module DiffsHelper
end

app/views/diffs/index.html.erb
<h1 id="top">Changes for <%= l last.created_at.to_date %></h1>

<div class="alert--info">No changes found!</div>

app/views/diffs/show.html.erb
<div class="autogrid txtcenter">
	<% @dates.each do |date| %>
		<%= content_tag :div, class: (:current if @date == date) do
			link_to l(date), diff_path(date)
		end %>
	<% end %>
</div>

<h1 id="top">Changes for <%= l @date %></h1>

<% if @diffs.empty? %>
	<div class="alert--info">No changes found!</div>
<% end %>

<% @diffs.each do |diff|
	site = diff.site %>
	<div class="grid-10">
		<div class="col-9">
			<h3><%= link_to (site.name || site.url), site.url %></h3>
		</div>
		<div class="txtright">
			<%= link_to "↑ Top ↑", '#top' %>
		</div>
	</div>
	<ul class="unstyled mls">
		<% diff.content.each do |chunk| %>
			<li>
				<%=
					target = chunk['target']
					if target
						target = Target.from_h target
						content_tag :h4, target
					end
				%>
				<%=
					chunk = chunk['diff']
					raw Diffy::Diff.load(chunk).to_s :html
				%>
			</li>
		<% end %>
	</ul>
<% end %>