config/routes.rb
Rails.application.routes.draw do
	resources :diffs, only: %i[index show]
	resources :sites, only: %i[index show new create edit update destroy]
	resources :config, only: %i[index]
	resources :groups, only: %i[new create edit update destroy]
	resources :templates, only: %i[new create edit update destroy]
	# resources :access, only: %i[new create]

	get '/login', to: 'site#login'
	post '/login', to: 'site#auth'
	get '/logout', to: 'site#logout'
end

app/controllers/config_controller.rb
class ConfigController < ApplicationController
	def index
		@groups = Group.all
		@templates = ::Template.all
		@sites = Site.where(group: nil).order(:name, :url)
	end
end

app/helpers/config_helper.rb
module ConfigHelper
end

app/views/config/index.html.erb
<div class="tabs js-tabs">
	<nav class="tabs-menu">
		<a href="#tab-groups" class="tabs-menu-link is-active"><%= t(:groups) %></a>
		<a href="#tab-templates" class="tabs-menu-link"><%= t(:templates) %></a>
		<a href="#tab-sites" class="tabs-menu-link"><%= t(:sites_without_group) %></a>
	</nav>
	<div class="tabs-content">
		<div id="tab-groups" class="tabs-content-item">
			<div class="mbs">
				<%= link_to t(:new_group), new_group_path %>
			</div>

			<ul class="unstyled">
			<% @groups.each do |group| %>
				<li><%= link_to (group.name||group.id), edit_group_path(group) %>
					<% if session[:authenticated] %>
						 |
						<%= link_to :remove, group, method: :delete, data: { confirm: "Are you sure you want to remove this group ("+(group.name||group.id)+") and all related data? This cannot be revert!" } %>
					<% end %>
				</li>
				<% if group.targets %>
					<ul>
						<li><%= :targets %>:</li>
						<ul>
							<% group.targets.each do |target| %>
								<li><%= :name %>: <%= target.name||target.id %></li>
								<% unless target.css.blank? %>
									<li class="separator"><%= :css %>: <%= content_tag :code do target.css end %></li>
								<% else %>
									<li><%= :from %>: <%= content_tag :code do target.from end %></li>
									<li class="separator"><%= :to %>: <%= content_tag :code do target.to end %></li>
								<% end %>
							<% end %>
						</ul>
					</ul>
				<% end %>
				<% if group.template %>
					<ul>
						<li><%= :template %>:</li>
						<ul>
							<li><%= :template %>: <%= group.template.name||group.template.id %></li>
						</ul>
					</ul>
				<% end %>
				<% unless group.sites.empty? %>
					<ul class="sites">
						<li><%= t(:list_of) %> <%= group.sites.count %> sites: <button></button></li>
						<ul class="hidden">
							<% group.sites.order(:name, :url).each do |site| %>
								<li><%= link_to (site.name || site.url), site %></li>
							<% end %>
						</ul>
					</ul>
				<% end %>
			<% end %>
			</ul>

			<div class="mts">
				<%= link_to t(:new_group), new_group_path %>
			</div>
		</div>
		<div id="tab-templates" class="tabs-content-item">
			<div class="mbs">
				<%= link_to t(:new_template), new_template_path %>
			</div>

			<ul class="unstyled">
				<% @templates.each do |template| %>
					<li>
						<%= link_to (template.name||template.id), edit_template_path(template) %>
						<% if session[:authenticated] %>
							 |
							<%= link_to :remove, template, method: :delete, data: { confirm: "Are you sure you want to remove this template ("+(template.name||template.id)+") and all related data? This cannot be revert!" } %>
						<% end %>
					</li>
					<% unless template.targets.empty? %>
						<ul>
							<li><%= :targets %>:</li>
							<ul>
								<% template.targets.each do |target| %>
									<li><%= :name %>: <%= target.name||target.id %></li>
									<% unless target.css.blank? %>
										<li class="separator"><%= :css %>: <%= content_tag :code do target.css end %></li>
									<% else %>
										<li><%= :from %>: <%= content_tag :code do target.from end %></li>
										<li class="separator"><%= :to %>: <%= content_tag :code do target.to end %></li>
									<% end %>
								<% end %>
							</ul>
						</ul>
					<% end %>
				<% end %>
			</ul>

			<div class="mts">
				<%= link_to t(:new_template), new_template_path %>
			</div>
		</div>
		<div id="tab-sites" class="tabs-content-item">
			<div class="mbs">
				<%= link_to t(:new_site), new_site_path %>
			</div>

			<ul class="unstyled">
				<% @sites.each do |site| %>
					<li>
						<%= link_to (site.name||site.url), edit_site_path(site) %> |
						<%= link_to :show, site %>
						<% if session[:authenticated] %>
							 |
							<%= link_to :remove, site, method: :delete, data: { confirm: "Are you sure you want to remove this site ("+(site.name||site.id)+") and all related data? This cannot be revert!" } %>
						<% end %>
					</li>
					<% unless site.targets.empty? %>
						<ul>
							<li><%= :targets %>:</li>
							<ul>
							<% site.targets.each do |target| %>
								<li><%= :name %>: <%= target.name||target.id %></li>
								<% unless target.css.blank? %>
									<li><%= :css %>: <%= content_tag :code do target.css end %></li>
								<% else %>
									<li><%= :from %>: <%= content_tag :code do target.from end %></li>
									<li><%= :to %>: <%= content_tag :code do target.to end %></li>
								<% end %>
							<% end %>
							</ul>
						</ul>
					<% end %>
					<% if site.template %>
					<ul>
						<li><%= :template %>: <%= site.template.name||site.template.id %></li>
					</ul>
					<% end %>
				<% end %>
			</ul>

			<div class="mts">
				<%= link_to t(:new_site), new_site_path %>
			</div>
		</div>
	</div>
</div>