config/routes.rb
Rails.application.routes.draw do
	resources :diffs, only: %i[index show]
	resources :sites, only: %i[index show new create edit update destroy]
	resources :config, only: %i[index]
	resources :groups, only: %i[new create edit update destroy]
	resources :templates, only: %i[new create edit update destroy]
	# resources :access, only: %i[new create]

	get '/login', to: 'site#login'
	post '/login', to: 'site#auth'
	get '/logout', to: 'site#logout'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def authenticated?
		session[:authenticated] == true
	end

	def must_be_authenticated
		unless authenticated?
			session[:redirect_to] = request.path
			redirect_to login_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields_below(name, f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end

		link_to(name, '#', class: "add_fields_below", data: {id: id, fields: fields.gsub("\n", "")})
	end

	def link_to_add_fields(name, f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end

		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
	end

	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	end
end

app/views/application/_footer.erb
<footer class="mam">
	<div>
		Icons made by <a href="https://www.flaticon.com/authors/roundicons" title="Roundicons">Roundicons</a>
		from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by
		<a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>.
	</div>
	<div>
		Icons modified and adaptated by <a href="https://norore.fr" title="Norore">Norore</a>.
	</div>
</footer>

app/views/application/_headers.erb
<header>
	<h1>Alice</h1>
	<nav>
		<ul>
			<li>
				<span id="changes"> </span><%= link_to 'Changes', diffs_path %>
			</li>
			<li>
				<span id="sites"> </span><%= link_to 'Sites', sites_path %>
			</li>
			<li>
				<span id="config"> </span><%= link_to 'Config', config_index_path %>
			</li>
		</ul>
	</nav>
</header>